name: CI-SFTP
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: 46.36.216.127
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          
          local_path: ./*

          remote_path: /var/www/receiver_lea_usr/data/www/receiver-leads.easy-mo.ru/receiver-leads/testfolder
          
          args: '-o ConnectTimeout=5'
