name: CI-SFTP
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: 46.36.216.127
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www/receiver_lea_usr/data/www/receiver-leads.easy-mo.ru/receiver-leads/testfolder
          
          # sftp args
          args: '-o ConnectTimeout=5'
